//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// LCT.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_FRM_MAIN                    101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_LCTTYPE                     130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DLG_SET                     312
#define IDD_DLG_MODEL                   313
#define IDC_DISPLAY                     1001
#define IDC_BUTTON1                     1003
#define IDC_BUTTON2                     1004
#define IDC_BUTTON3                     1005
#define IDC_BUTTON4                     1006
#define IDC_BUTTON5                     1007
#define IDC_BUTTON6                     1008
#define IDC_BUTTON7                     1009
#define IDC_BUTTON8                     1010
#define IDC_BUTTON9                     1011
#define IDC_SET_BTN                     1012
#define IDC_EDT_XCNT                    1012
#define IDC_EDT_YCNT                    1013
#define IDC_GRID1                       1013
#define IDC_EDT_XSIZE                   1014
#define IDC_GRID2                       1014
#define IDC_EDT_YSIZE                   1015
#define IDC_SCORE_ON1                   1015
#define IDC_EDT_XGAP                    1016
#define IDC_SCORE_ON2                   1016
#define IDC_EDT_YGAP                    1017
#define IDC_DISP_RESULT1                1017
#define IDC_EDT_SCORE                   1018
#define IDC_DISP_RESULT2                1018
#define IDC_BUTTON10                    1019
#define IDC_EDT_XPOS                    1020
#define IDC_BUTTON11                    1020
#define IDC_SCORE_MODE1                 1020
#define IDC_EDT_YPOS                    1021
#define IDC_SKIP                        1021
#define IDC_JOG_UP                      1022
#define IDC_SCORE_MODE2                 1022
#define IDC_JOG_DOWN                    1023
#define IDC_DISP_LOGO                   1023
#define IDC_JOG_LEFT                    1024
#define IDC_MODEL_LIST                  1024
#define IDC_SCORE_MODE3                 1024
#define IDC_JOG_RIGHT                   1025
#define IDC_MODEL_NAME                  1025
#define IDC_JOG_DOWN2                   1026
#define IDC_EDT_MODEL                   1026
#define IDC_BUTTON12                    1027
#define IDC_ADD_BTN                     1027
#define IDC_RESULT1                     1027
#define IDC_RESULTV1                    1027
#define IDC_EDT_SCORE2                  1028
#define IDC_EDT_SCORE_EMT               1028
#define IDC_DELETE_BTN                  1028
#define IDC_RESULT2                     1028
#define IDC_EDT_OK_RANGE_MIN            1028
#define IDC_RESULTV2                    1028
#define IDC_OK_BTN                      1029
#define IDC_BUTTON13                    1029
#define IDC_RESULT3                     1029
#define IDC_LOAD_BTN                    1030
#define IDC_EDT_SCORE_NG_MIN            1030
#define IDC_EDT_BLUE_R                  1030
#define IDC_RESULT4                     1030
#define IDC_BUTTON14                    1031
#define IDC_SET_MODE1                   1031
#define IDC_RESULTV3                    1031
#define IDC_EDT_SCORE_NG_MAX            1032
#define IDC_EDT_BLUE_COUNT              1032
#define IDC_SET_MODE2                   1032
#define IDC_EDT_YPOS2                   1033
#define IDC_EDT_PITCH                   1033
#define IDC_BUTTON15                    1034
#define IDC_BLUE_SCORE_MIN              1035
#define IDC_EDT_BLUE_G                  1035
#define IDC_BUTTON16                    1036
#define IDC_BLUE_SCORE_MAX              1037
#define IDC_EDT_BLUE_B                  1037
#define IDC_BUTTON17                    1038
#define IDC_BLACK_SCORE_MIN             1039
#define IDC_EDT_BLACK_R                 1039
#define IDC_BUTTON18                    1040
#define IDC_BLACK_SCORE_MAX             1041
#define IDC_EDT_BLACK_COUNT             1041
#define IDC_EDT_BIG_R                   1041
#define IDC_BUTTON19                    1042
#define IDC_BUTTON20                    1043
#define IDC_BLUE_VALUE                  1044
#define IDC_BUTTON21                    1044
#define IDC_BLACK_VALUE                 1045
#define IDC_LINE_LENGTH                 1046
#define IDC_LENS_IN_SCORE               1046
#define IDC_BUTTON22                    1047
#define IDC_LINE_COUNT                  1048
#define IDC_IN_BOX_SIZE                 1048
#define IDC_BUTTON23                    1049
#define IDC_INBOX_SIZE_X                1050
#define IDC_EDT_BLACK_G                 1051
#define IDC_BUTTON24                    1052
#define IDC_EDT_BLACK_B                 1053
#define IDC_BUTTON25                    1054
#define IDC_IDC_EDT_BIG_G               1054
#define IDC_NG_SIZE                     1055
#define IDC_EDT_OK_RANGE_MAX            1055
#define IDC_BUTTON27                    1056
#define IDC_EDT_NG_THR                  1057
#define IDC_BUTTON28                    1058
#define IDC_EDT_BLUE_SCORE              1059
#define IDC_BUTTON29                    1060
#define IDC_EDT_BLUE_RCHK               1061
#define IDC_BUTTON30                    1062
#define IDC_EDT_BLUE_GCHK               1063
#define IDC_BUTTON31                    1064
#define IDC_EDT_BLUE_BCHK               1065
#define IDC_BUTTON32                    1066
#define IDC_IN_BOX_SIZEY                1067

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        314
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
